# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.startbutton_easy = QtWidgets.QPushButton(self.tab)
        self.startbutton_easy.setGeometry(QtCore.QRect(30, 280, 151, 71))
        self.startbutton_easy.clicked.connect(self.startbutton_easy_clicked)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startbutton_easy.setFont(font)
        self.startbutton_easy.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.startbutton_easy.setObjectName("startbutton_easy")
        self.stopbutton_easy = QtWidgets.QPushButton(self.tab)
        self.stopbutton_easy.setGeometry(QtCore.QRect(230, 280, 151, 71))
        self.stopbutton_easy.clicked.connect(self.stopbutton_easy_clicked)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopbutton_easy.setFont(font)
        self.stopbutton_easy.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.stopbutton_easy.setObjectName("stopbutton_easy")
        self.button_prog1 = QtWidgets.QPushButton(self.tab)
        self.button_prog1.setGeometry(QtCore.QRect(30, 60, 120, 75))
        self.button_prog1.setObjectName("button_prog1")
        self.button_prog1.clicked.connect(self.program1)
        self.button_prog3 = QtWidgets.QPushButton(self.tab)
        self.button_prog3.setGeometry(QtCore.QRect(370, 60, 120, 75))
        self.button_prog3.setObjectName("button_prog3")
        self.button_prog3.clicked.connect(self.program3)
        self.button_prog4 = QtWidgets.QPushButton(self.tab)
        self.button_prog4.setGeometry(QtCore.QRect(540, 60, 120, 75))
        self.button_prog4.setObjectName("button_prog4")
        self.button_prog4.clicked.connect(self.program4)
        self.textBrowser_progselected = QtWidgets.QTextBrowser(self.tab)
        self.textBrowser_progselected.setGeometry(QtCore.QRect(170, 190, 256, 41))
        self.textBrowser_progselected.setObjectName("textBrowser_progselected")
        self.label_progselected = QtWidgets.QLabel(self.tab)
        self.label_progselected.setGeometry(QtCore.QRect(30, 200, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_progselected.setFont(font)
        self.label_progselected.setObjectName("label_progselected")
        self.button_prog2 = QtWidgets.QPushButton(self.tab)
        self.button_prog2.setGeometry(QtCore.QRect(200, 60, 120, 75))
        self.button_prog2.setObjectName("button_prog2")
        self.button_prog2.clicked.connect(self.program2)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.layoutWidget = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 531, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_sliders = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_sliders.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_sliders.setObjectName("horizontalLayout_sliders")

        self.slider_heave = QtWidgets.QSlider(self.layoutWidget)
        self.slider_heave.setOrientation(QtCore.Qt.Vertical)
        self.slider_heave.setObjectName("slider_heave")
        self.slider_heave.setMinimum(0)
        self.slider_heave.setMaximum(10)
        self.slider_heave.valueChanged.connect(self.heave_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_heave)

        self.slider_surge = QtWidgets.QSlider(self.layoutWidget)
        self.slider_surge.setOrientation(QtCore.Qt.Vertical)
        self.slider_surge.setObjectName("slider_surge")
        self.slider_surge.setMinimum(0)
        self.slider_surge.setMaximum(10)
        self.slider_surge.valueChanged.connect(self.surge_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_surge)

        self.slider_sway = QtWidgets.QSlider(self.layoutWidget)
        self.slider_sway.setOrientation(QtCore.Qt.Vertical)
        self.slider_sway.setObjectName("slider_sway")
        self.slider_sway.setMinimum(0)
        self.slider_sway.setMaximum(10)
        self.slider_sway.valueChanged.connect(self.sway_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_sway)

        self.slider_roll = QtWidgets.QSlider(self.layoutWidget)
        self.slider_roll.setOrientation(QtCore.Qt.Vertical)
        self.slider_roll.setObjectName("slider_roll")
        self.slider_roll.setMinimum(0)
        self.slider_roll.setMaximum(10)
        self.slider_roll.valueChanged.connect(self.roll_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_roll)

        self.slider_pitch = QtWidgets.QSlider(self.layoutWidget)
        self.slider_pitch.setOrientation(QtCore.Qt.Vertical)
        self.slider_pitch.setObjectName("slider_pitch")
        self.slider_pitch.setMinimum(0)
        self.slider_pitch.setMaximum(10)
        self.slider_pitch.valueChanged.connect(self.pitch_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_pitch)

        self.slider_yaw = QtWidgets.QSlider(self.layoutWidget)
        self.slider_yaw.setOrientation(QtCore.Qt.Vertical)
        self.slider_yaw.setObjectName("slider_yaw")
        self.slider_yaw.setMinimum(0)
        self.slider_yaw.setMaximum(10)
        self.slider_yaw.valueChanged.connect(self.yaw_changed)
        self.horizontalLayout_sliders.addWidget(self.slider_yaw)

        self.label_yaw = QtWidgets.QLabel(self.tab_2)
        self.label_yaw.setGeometry(QtCore.QRect(460, 230, 41, 16))
        self.label_yaw.setObjectName("label_yaw")
        self.label_rotfreq_value = QtWidgets.QLabel(self.tab_2)
        self.label_rotfreq_value.setGeometry(QtCore.QRect(690, 20, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_rotfreq_value.setFont(font)
        self.label_rotfreq_value.setObjectName("label_rotfreq_value")
        self.label_sway = QtWidgets.QLabel(self.tab_2)
        self.label_sway.setGeometry(QtCore.QRect(220, 230, 51, 16))
        self.label_sway.setObjectName("label_sway")
        self.stopbutton_advanced = QtWidgets.QPushButton(self.tab_2)
        self.stopbutton_advanced.setGeometry(QtCore.QRect(230, 280, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.stopbutton_advanced.setFont(font)
        self.stopbutton_advanced.setAutoFillBackground(False)
        self.stopbutton_advanced.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.stopbutton_advanced.setObjectName("stopbutton_advanced")
        self.stopbutton_advanced.clicked.connect(self.stopbutton_advanced_clicked)
        self.label_surge_value = QtWidgets.QLabel(self.tab_2)
        self.label_surge_value.setGeometry(QtCore.QRect(150, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_surge_value.setFont(font)
        self.label_surge_value.setObjectName("label_surge_value")
        self.label_freq = QtWidgets.QLabel(self.tab_2)
        self.label_freq.setGeometry(QtCore.QRect(580, 230, 90, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_freq.setFont(font)
        self.label_freq.setObjectName("label_freq")
        self.label_heave_value = QtWidgets.QLabel(self.tab_2)
        self.label_heave_value.setGeometry(QtCore.QRect(70, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_heave_value.setFont(font)
        self.label_heave_value.setObjectName("label_heave_value")
        self.label_sway_value = QtWidgets.QLabel(self.tab_2)
        self.label_sway_value.setGeometry(QtCore.QRect(220, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_sway_value.setFont(font)
        self.label_sway_value.setObjectName("label_sway_value")
        self.layoutWidget_2 = QtWidgets.QWidget(self.tab_2)
        self.layoutWidget_2.setGeometry(QtCore.QRect(580, 60, 171, 161))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_sliders2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_sliders2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_sliders2.setObjectName("horizontalLayout_sliders2")
        self.slider_transfreq = QtWidgets.QSlider(self.layoutWidget_2)
        self.slider_transfreq.setOrientation(QtCore.Qt.Vertical)
        self.slider_transfreq.setObjectName("slider_transfreq")
        self.slider_transfreq.setMinimum(1)
        self.slider_transfreq.setMaximum(10)
        self.slider_transfreq.valueChanged.connect(self.transfreq_changed)
        self.horizontalLayout_sliders2.addWidget(self.slider_transfreq)
        self.slider_rotfreq = QtWidgets.QSlider(self.layoutWidget_2)
        self.slider_rotfreq.setOrientation(QtCore.Qt.Vertical)
        self.slider_rotfreq.setObjectName("slider_rotfreq")
        self.slider_rotfreq.setMinimum(1)
        self.slider_rotfreq.setMaximum(10)
        self.slider_rotfreq.valueChanged.connect(self.rotfreq_changed)
        self.horizontalLayout_sliders2.addWidget(self.slider_rotfreq)
        self.label_speed = QtWidgets.QLabel(self.tab_2)
        self.label_speed.setGeometry(QtCore.QRect(680, 230, 70, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_speed.setFont(font)
        self.label_speed.setObjectName("label_speed")
        self.textBrowser_status = QtWidgets.QTextBrowser(self.tab_2)
        self.textBrowser_status.setGeometry(QtCore.QRect(520, 280, 241, 71))
        self.textBrowser_status.setObjectName("textBrowser_status")
        self.label_yaw_value = QtWidgets.QLabel(self.tab_2)
        self.label_yaw_value.setGeometry(QtCore.QRect(470, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_yaw_value.setFont(font)
        self.label_yaw_value.setObjectName("label_yaw_value")
        self.label_pitch_value = QtWidgets.QLabel(self.tab_2)
        self.label_pitch_value.setGeometry(QtCore.QRect(380, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_pitch_value.setFont(font)
        self.label_pitch_value.setObjectName("label_pitch_value")
        self.label_transfreq_value = QtWidgets.QLabel(self.tab_2)
        self.label_transfreq_value.setGeometry(QtCore.QRect(620, 20, 31, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_transfreq_value.setFont(font)
        self.label_transfreq_value.setObjectName("label_transfreq_value")
        self.label_heave = QtWidgets.QLabel(self.tab_2)
        self.label_heave.setGeometry(QtCore.QRect(45, 230, 60, 20))
        self.label_heave.setObjectName("label_heave")
        self.label_surge = QtWidgets.QLabel(self.tab_2)
        self.label_surge.setGeometry(QtCore.QRect(125, 230, 61, 16))
        self.label_surge.setObjectName("label_surge")
        self.label_roll = QtWidgets.QLabel(self.tab_2)
        self.label_roll.setGeometry(QtCore.QRect(300, 230, 41, 16))
        self.label_roll.setObjectName("label_roll")
        self.startbutton_advanced = QtWidgets.QPushButton(self.tab_2)
        self.startbutton_advanced.setGeometry(QtCore.QRect(30, 280, 151, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.startbutton_advanced.setFont(font)
        self.startbutton_advanced.setAutoFillBackground(False)
        self.startbutton_advanced.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.startbutton_advanced.setObjectName("startbutton_advanced")
        self.startbutton_advanced.clicked.connect(self.startbutton_advanced_clicked)
        self.start_active = 0
        self.label_roll_value = QtWidgets.QLabel(self.tab_2)
        self.label_roll_value.setGeometry(QtCore.QRect(300, 20, 30, 25))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_roll_value.setFont(font)
        self.label_roll_value.setObjectName("label_roll_value")
        self.label_pitch = QtWidgets.QLabel(self.tab_2)
        self.label_pitch.setGeometry(QtCore.QRect(370, 230, 61, 16))
        self.label_pitch.setObjectName("label_pitch")
        self.label_status = QtWidgets.QLabel(self.tab_2)
        self.label_status.setGeometry(QtCore.QRect(430, 310, 90, 20))
        self.label_status.setObjectName("label_status")
        self.tabWidget.addTab(self.tab_2, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Stewart Platform GUI"))
        self.startbutton_easy.setText(_translate("MainWindow", "START"))
        MainWindow.setWindowIcon(QtGui.QIcon('StewartPlatform.png'))
        self.stopbutton_easy.setText(_translate("MainWindow", "STOP"))
        self.button_prog1.setText(_translate("MainWindow", "Wave 1"))
        self.button_prog3.setText(_translate("MainWindow", "Fixed Path"))
        self.button_prog4.setText(_translate("MainWindow", "Reset"))
        self.label_progselected.setText(_translate("MainWindow", "Program selected:"))
        self.button_prog2.setText(_translate("MainWindow", "Wave 2"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Basic"))
        self.label_yaw.setText(_translate("MainWindow", "YAW"))
        self.label_rotfreq_value.setText(_translate("MainWindow", "1"))
        self.label_sway.setText(_translate("MainWindow", "SWAY"))
        self.stopbutton_advanced.setText(_translate("MainWindow", "STOP"))
        self.label_surge_value.setText(_translate("MainWindow", "0"))
        self.label_freq.setText(_translate("MainWindow", "TRANS FREQ"))
        self.label_heave_value.setText(_translate("MainWindow", "0"))
        self.label_sway_value.setText(_translate("MainWindow", "0"))
        self.label_speed.setText(_translate("MainWindow", "ROT FREQ"))
        self.label_yaw_value.setText(_translate("MainWindow", "0"))
        self.label_pitch_value.setText(_translate("MainWindow", "0"))
        self.label_transfreq_value.setText(_translate("MainWindow", "1"))
        self.label_heave.setText(_translate("MainWindow", "HEAVE"))
        self.label_surge.setText(_translate("MainWindow", "SURGE"))
        self.label_roll.setText(_translate("MainWindow", "ROLL"))
        self.startbutton_advanced.setText(_translate("MainWindow", "START"))
        self.label_roll_value.setText(_translate("MainWindow", "0"))
        self.label_pitch.setText(_translate("MainWindow", "PITCH"))
        self.label_status.setText(_translate("MainWindow", "STATUS:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Advanced"))